import Head from 'next/head'
import Layout, { siteTitle } from '../components/layout'
import utilStyles from '../styles/utils.module.css'
import { getSortedPostsData } from '../lib/posts'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}

export default function Home({ allPostsData }) {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
      </Head>
{/*       
      <main className={styles.main}>
       

        <div className={styles.grid}>
  

          <a href="/general-surveys/first-survey.js" className={styles.card}>
            <h3>Learn &rarr;</h3>
            <p>Find out what UserDAO is and how it works</p>
          </a>

          <a
            href="/first-"
            className={styles.card}
          >
            <h3>Get Data &rarr;</h3>
            <p>Purchuse access to datasets generated by UserDAO</p>
          </a>

          <a
            href="https://vercel.com/import?filter=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h3>Join &rarr;</h3>
            <p>
              Recieve a share of revenue produced by UserDAO
            </p>
          </a>
        </div>
      </main> */}

      <section className={utilStyles.headingMd}>
        <p>Payed for Opinions</p>
      </section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map(({ id, date, title }) => (
            <li className={utilStyles.listItem} key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  )
}
